---
all:
  children:
    webservers:
      hosts:
        staging01:
          ansible_host: 2.3.4.5
          ansible_port: 22
          server_name: staging.example.com
      vars:
        env: staging

  vars:
    ansible_user: deploy
    ansible_python_interpreter: /usr/bin/python3
    # Override fail2ban to be more lenient in staging
    fail2ban_maxretry: 20
    fail2ban_bantime: 300
