---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Test nginx config
  ansible.builtin.command: nginx -t
  changed_when: false
